name: blackbird
description: A boolean logic library for Dart and Flutter, allowing you to build trees of conditions and evaluate them.
version: 0.0.1
repository: https://github.com/btrautmann/blackbird

environment:
  sdk: ^3.3.1

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  uuid: ^4.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
